POST http://localhost:8080/api/validate/user/v1
Content-Type: application/json

{
  "age": 16,
  "birthday": "2002-01-01"
}

###
POST http://localhost:8080/api/validate/user/v2
Content-Type: application/json

{
  "age": 16,
  "birthday": "2002-01-01"
}